import { Registry } from "@/registry/schema"

const ui: Registry = [
  // {
  //   name: "accordion",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/accordion.vue"],
  // },
  // {
  //   name: "alert",
  //   type: "components:ui",
  //   files: ["ui/alert.vue"],
  // },
  // {
  //   name: "alert-dialog",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   registryDependencies: ["button"],
  //   files: ["ui/alert-dialog.vue"],
  // },
  // {
  //   name: "aspect-ratio",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/aspect-ratio.vue"],
  // },
  // {
  //   name: "avatar",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/avatar.vue"],
  // },
  // {
  //   name: "badge",
  //   type: "components:ui",
  //   files: ["ui/badge.vue"],
  // },
  // {
  //   name: "button",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/button.vue"],
  // },
  // {
  //   name: "calendar",
  //   type: "components:ui",
  //   dependencies: ["react-day-picker", "date-fns"],
  //   registryDependencies: ["button"],
  //   files: ["ui/calendar.vue"],
  // },
  // {
  //   name: "card",
  //   type: "components:ui",
  //   files: ["ui/card.vue"],
  // },
  // {
  //   name: "checkbox",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/checkbox.vue"],
  // },
  // {
  //   name: "collapsible",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/collapsible.vue"],
  // },
  // {
  //   name: "command",
  //   type: "components:ui",
  //   dependencies: ["cmdk"],
  //   registryDependencies: ["dialog"],
  //   files: ["ui/command.vue"],
  // },
  // {
  //   name: "context-menu",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/context-menu.vue"],
  // },
  // {
  //   name: "dialog",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/dialog.vue"],
  // },
  // {
  //   name: "dropdown-menu",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/dropdown-menu.vue"],
  // },
  // {
  //   name: "form",
  //   type: "components:ui",
  //   dependencies: [
  //     "@radix-ui/react-label",
  //     "@radix-ui/react-slot",
  //     "@hookform/resolvers",
  //     "zod",
  //     "react-hook-form",
  //   ],
  //   registryDependencies: ["button", "label"],
  //   files: ["ui/form.vue"],
  // },
  // {
  //   name: "hover-card",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/hover-card.vue"],
  // },
  // {
  //   name: "input",
  //   type: "components:ui",
  //   files: ["ui/input.vue"],
  // },
  // {
  //   name: "label",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/label.vue"],
  // },
  // {
  //   name: "menubar",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/menubar.vue"],
  // },
  // {
  //   name: "navigation-menu",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/navigation-menu.vue"],
  // },
  // {
  //   name: "popover",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/popover.vue"],
  // },
  // {
  //   name: "progress",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/progress.vue"],
  // },
  // {
  //   name: "radio-group",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/radio-group.vue"],
  // },
  // {
  //   name: "scroll-area",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/scroll-area.vue"],
  // },
  // {
  //   name: "select",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/select.vue"],
  // },
  // {
  //   name: "separator",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/separator.vue"],
  // },
  // {
  //   name: "sheet",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/sheet.vue"],
  // },
  // {
  //   name: "skeleton",
  //   type: "components:ui",
  //   files: ["ui/skeleton.vue"],
  // },
  // {
  //   name: "slider",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/slider.vue"],
  // },
  // {
  //   name: "switch",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/switch.vue"],
  // },
  // {
  //   name: "table",
  //   type: "components:ui",
  //   files: ["ui/table.vue"],
  // },
  // {
  //   name: "tabs",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/tabs.vue"],
  // },
  // {
  //   name: "textarea",
  //   type: "components:ui",
  //   files: ["ui/textarea.vue"],
  // },
  // {
  //   name: "toast",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/toast.vue", "ui/use-toast.ts", "ui/toaster.vue"],
  // },
  // {
  //   name: "toggle",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/toggle.vue"],
  // },
  // {
  //   name: "tooltip",
  //   type: "components:ui",
  //   dependencies: ["radix-vue"],
  //   files: ["ui/tooltip.vue"],
  // },
]

const example: Registry = [
  // {
  //   name: "accordion-demo",
  //   type: "components:example",
  //   registryDependencies: ["accordion"],
  //   files: ["example/accordion-demo.vue"],
  // },
  // {
  //   name: "alert-demo",
  //   type: "components:example",
  //   registryDependencies: ["alert"],
  //   files: ["example/alert-demo.vue"],
  // },
  // {
  //   name: "alert-destructive",
  //   type: "components:example",
  //   registryDependencies: ["alert"],
  //   files: ["example/alert-destructive.vue"],
  // },
  // {
  //   name: "alert-dialog-demo",
  //   type: "components:example",
  //   registryDependencies: ["alert-dialog", "button"],
  //   files: ["example/alert-dialog-demo.vue"],
  // },
  // {
  //   name: "aspect-ratio-demo",
  //   type: "components:example",
  //   registryDependencies: ["aspect-ratio"],
  //   files: ["example/aspect-ratio-demo.vue"],
  // },
  // {
  //   name: "avatar-demo",
  //   type: "components:example",
  //   registryDependencies: ["avatar"],
  //   files: ["example/avatar-demo.vue"],
  // },
  // {
  //   name: "badge-demo",
  //   type: "components:example",
  //   registryDependencies: ["badge"],
  //   files: ["example/badge-demo.vue"],
  // },
  // {
  //   name: "badge-destructive",
  //   type: "components:example",
  //   registryDependencies: ["badge"],
  //   files: ["example/badge-destructive.vue"],
  // },
  // {
  //   name: "badge-outline",
  //   type: "components:example",
  //   registryDependencies: ["badge"],
  //   files: ["example/badge-outline.vue"],
  // },
  // {
  //   name: "badge-secondary",
  //   type: "components:example",
  //   registryDependencies: ["badge"],
  //   files: ["example/badge-secondary.vue"],
  // },
  // {
  //   name: "button-demo",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-demo.vue"],
  // },
  // {
  //   name: "button-secondary",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-secondary.vue"],
  // },
  // {
  //   name: "button-destructive",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-destructive.vue"],
  // },
  // {
  //   name: "button-outline",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-outline.vue"],
  // },
  // {
  //   name: "button-ghost",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-ghost.vue"],
  // },
  // {
  //   name: "button-link",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-link.vue"],
  // },
  // {
  //   name: "button-with-icon",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-with-icon.vue"],
  // },
  // {
  //   name: "button-loading",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-loading.vue"],
  // },
  // {
  //   name: "button-icon",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-icon.vue"],
  // },
  // {
  //   name: "button-as-child",
  //   type: "components:example",
  //   registryDependencies: ["button"],
  //   files: ["example/button-as-child.vue"],
  // },
  // {
  //   name: "calendar-demo",
  //   type: "components:example",
  //   registryDependencies: ["calendar"],
  //   files: ["example/calendar-demo.vue"],
  // },
  // {
  //   name: "calendar-form",
  //   type: "components:example",
  //   registryDependencies: ["calendar", "form", "popover"],
  //   files: ["example/calendar-form.vue"],
  // },
  // {
  //   name: "card-demo",
  //   type: "components:example",
  //   registryDependencies: ["card", "button", "switch"],
  //   files: ["example/card-demo.vue"],
  // },
  // {
  //   name: "card-with-form",
  //   type: "components:example",
  //   registryDependencies: ["button", "card", "input", "label", "select"],
  //   files: ["example/card-with-form.vue"],
  // },
  // {
  //   name: "checkbox-demo",
  //   type: "components:example",
  //   registryDependencies: ["checkbox"],
  //   files: ["example/checkbox-demo.vue"],
  // },
  // {
  //   name: "checkbox-disabled",
  //   type: "components:example",
  //   registryDependencies: ["checkbox"],
  //   files: ["example/checkbox-disabled.vue"],
  // },
  // {
  //   name: "checkbox-form-multiple",
  //   type: "components:example",
  //   registryDependencies: ["checkbox", "form"],
  //   files: ["example/checkbox-form-multiple.vue"],
  // },
  // {
  //   name: "checkbox-form-single",
  //   type: "components:example",
  //   registryDependencies: ["checkbox", "form"],
  //   files: ["example/checkbox-form-single.vue"],
  // },
  // {
  //   name: "checkbox-with-text",
  //   type: "components:example",
  //   registryDependencies: ["checkbox"],
  //   files: ["example/checkbox-with-text.vue"],
  // },
  // {
  //   name: "collapsible-demo",
  //   type: "components:example",
  //   registryDependencies: ["collapsible"],
  //   files: ["example/collapsible-demo.vue"],
  // },
  // {
  //   name: "combobox-demo",
  //   type: "components:example",
  //   registryDependencies: ["command"],
  //   files: ["example/combobox-demo.vue"],
  // },
  // {
  //   name: "combobox-dropdown-menu",
  //   type: "components:example",
  //   registryDependencies: ["command", "dropdown-menu", "button"],
  //   files: ["example/combobox-dropdown-menu.vue"],
  // },
  // {
  //   name: "combobox-form",
  //   type: "components:example",
  //   registryDependencies: ["command", "form"],
  //   files: ["example/combobox-form.vue"],
  // },
  // {
  //   name: "combobox-popover",
  //   type: "components:example",
  //   registryDependencies: ["combobox", "popover"],
  //   files: ["example/combobox-popover.vue"],
  // },
  // {
  //   name: "command-demo",
  //   type: "components:example",
  //   registryDependencies: ["command"],
  //   files: ["example/command-demo.vue"],
  // },
  // {
  //   name: "command-dialog",
  //   type: "components:example",
  //   registryDependencies: ["command", "dialog"],
  //   files: ["example/command-dialog.vue"],
  // },
  // {
  //   name: "context-menu-demo",
  //   type: "components:example",
  //   registryDependencies: ["context-menu"],
  //   files: ["example/context-menu-demo.vue"],
  // },
  // {
  //   name: "data-table-demo",
  //   type: "components:example",
  //   registryDependencies: ["data-table"],
  //   files: ["example/data-table-demo.vue"],
  // },
  // {
  //   name: "date-picker-demo",
  //   type: "components:example",
  //   registryDependencies: ["button", "calendar", "popover"],
  //   files: ["example/date-picker-demo.vue"],
  //   dependencies: ["date-fns"],
  // },
  // {
  //   name: "date-picker-form",
  //   type: "components:example",
  //   registryDependencies: ["button", "calendar", "form", "popover"],
  //   files: ["example/date-picker-form.vue"],
  //   dependencies: ["date-fns"],
  // },
  // {
  //   name: "date-picker-with-presets",
  //   type: "components:example",
  //   registryDependencies: ["button", "calendar", "popover", "select"],
  //   files: ["example/date-picker-with-presets.vue"],
  //   dependencies: ["date-fns"],
  // },
  // {
  //   name: "date-picker-with-range",
  //   type: "components:example",
  //   registryDependencies: ["button", "calendar", "popover"],
  //   files: ["example/date-picker-with-range.vue"],
  //   dependencies: ["date-fns"],
  // },
  // {
  //   name: "dialog-demo",
  //   type: "components:example",
  //   registryDependencies: ["dialog"],
  //   files: ["example/dialog-demo.vue"],
  // },
  // {
  //   name: "dropdown-menu-demo",
  //   type: "components:example",
  //   registryDependencies: ["dropdown-menu"],
  //   files: ["example/dropdown-menu-demo.vue"],
  // },
  // {
  //   name: "dropdown-menu-checkboxes",
  //   type: "components:example",
  //   registryDependencies: ["dropdown-menu", "checkbox"],
  //   files: ["example/dropdown-menu-checkboxes.vue"],
  // },
  // {
  //   name: "dropdown-menu-radio-group",
  //   type: "components:example",
  //   registryDependencies: ["dropdown-menu", "radio-group"],
  //   files: ["example/dropdown-menu-radio-group.vue"],
  // },
  // {
  //   name: "hover-card-demo",
  //   type: "components:example",
  //   registryDependencies: ["hover-card"],
  //   files: ["example/hover-card-demo.vue"],
  // },
  // {
  //   name: "input-demo",
  //   type: "components:example",
  //   registryDependencies: ["input"],
  //   files: ["example/input-demo.vue"],
  // },
  // {
  //   name: "input-disabled",
  //   type: "components:example",
  //   registryDependencies: ["input"],
  //   files: ["example/input-disabled.vue"],
  // },
  // {
  //   name: "input-file",
  //   type: "components:example",
  //   registryDependencies: ["input"],
  //   files: ["example/input-file.vue"],
  // },
  // {
  //   name: "input-form",
  //   type: "components:example",
  //   registryDependencies: ["input", "button", "form"],
  //   files: ["example/input-form.vue"],
  // },
  // {
  //   name: "input-with-button",
  //   type: "components:example",
  //   registryDependencies: ["input", "button"],
  //   files: ["example/input-with-button.vue"],
  // },
  // {
  //   name: "input-with-label",
  //   type: "components:example",
  //   registryDependencies: ["input", "button", "label"],
  //   files: ["example/input-with-label.vue"],
  // },
  // {
  //   name: "input-with-text",
  //   type: "components:example",
  //   registryDependencies: ["input", "button", "label"],
  //   files: ["example/input-with-text.vue"],
  // },
  // {
  //   name: "label-demo",
  //   type: "components:example",
  //   registryDependencies: ["label"],
  //   files: ["example/label-demo.vue"],
  // },
  // {
  //   name: "menubar-demo",
  //   type: "components:example",
  //   registryDependencies: ["menubar"],
  //   files: ["example/menubar-demo.vue"],
  // },
  // {
  //   name: "navigation-menu-demo",
  //   type: "components:example",
  //   registryDependencies: ["navigation-menu"],
  //   files: ["example/navigation-menu-demo.vue"],
  // },
  // {
  //   name: "popover-demo",
  //   type: "components:example",
  //   registryDependencies: ["popover"],
  //   files: ["example/popover-demo.vue"],
  // },
  // {
  //   name: "progress-demo",
  //   type: "components:example",
  //   registryDependencies: ["progress"],
  //   files: ["example/progress-demo.vue"],
  // },
  // {
  //   name: "radio-group-demo",
  //   type: "components:example",
  //   registryDependencies: ["radio-group"],
  //   files: ["example/radio-group-demo.vue"],
  // },
  // {
  //   name: "radio-group-form",
  //   type: "components:example",
  //   registryDependencies: ["radio-group", "form"],
  //   files: ["example/radio-group-form.vue"],
  // },
  // {
  //   name: "scroll-area-demo",
  //   type: "components:example",
  //   registryDependencies: ["scroll-area"],
  //   files: ["example/scroll-area-demo.vue"],
  // },
  // {
  //   name: "select-demo",
  //   type: "components:example",
  //   registryDependencies: ["select"],
  //   files: ["example/select-demo.vue"],
  // },
  // {
  //   name: "select-form",
  //   type: "components:example",
  //   registryDependencies: ["select"],
  //   files: ["example/select-form.vue"],
  // },
  // {
  //   name: "separator-demo",
  //   type: "components:example",
  //   registryDependencies: ["separator"],
  //   files: ["example/separator-demo.vue"],
  // },
  // {
  //   name: "sheet-demo",
  //   type: "components:example",
  //   registryDependencies: ["sheet"],
  //   files: ["example/sheet-demo.vue"],
  // },
  // {
  //   name: "sheet-side",
  //   type: "components:example",
  //   registryDependencies: ["sheet"],
  //   files: ["example/sheet-side.vue"],
  // },
  // {
  //   name: "skeleton-demo",
  //   type: "components:example",
  //   registryDependencies: ["skeleton"],
  //   files: ["example/skeleton-demo.vue"],
  // },
  // {
  //   name: "slider-demo",
  //   type: "components:example",
  //   registryDependencies: ["slider"],
  //   files: ["example/slider-demo.vue"],
  // },
  // {
  //   name: "switch-demo",
  //   type: "components:example",
  //   registryDependencies: ["switch"],
  //   files: ["example/switch-demo.vue"],
  // },
  // {
  //   name: "switch-form",
  //   type: "components:example",
  //   registryDependencies: ["switch", "form"],
  //   files: ["example/switch-form.vue"],
  // },
  // {
  //   name: "table-demo",
  //   type: "components:example",
  //   registryDependencies: ["table"],
  //   files: ["example/table-demo.vue"],
  // },
  // {
  //   name: "tabs-demo",
  //   type: "components:example",
  //   registryDependencies: ["tabs"],
  //   files: ["example/tabs-demo.vue"],
  // },
  // {
  //   name: "textarea-demo",
  //   type: "components:example",
  //   registryDependencies: ["textarea"],
  //   files: ["example/textarea-demo.vue"],
  // },
  // {
  //   name: "textarea-disabled",
  //   type: "components:example",
  //   registryDependencies: ["textarea"],
  //   files: ["example/textarea-disabled.vue"],
  // },
  // {
  //   name: "textarea-form",
  //   type: "components:example",
  //   registryDependencies: ["textarea", "form"],
  //   files: ["example/textarea-form.vue"],
  // },
  // {
  //   name: "textarea-with-button",
  //   type: "components:example",
  //   registryDependencies: ["textarea", "button"],
  //   files: ["example/textarea-with-button.vue"],
  // },
  // {
  //   name: "textarea-with-label",
  //   type: "components:example",
  //   registryDependencies: ["textarea", "label"],
  //   files: ["example/textarea-with-label.vue"],
  // },
  // {
  //   name: "textarea-with-text",
  //   type: "components:example",
  //   registryDependencies: ["textarea", "label"],
  //   files: ["example/textarea-with-text.vue"],
  // },
  // {
  //   name: "toast-demo",
  //   type: "components:example",
  //   registryDependencies: ["toast"],
  //   files: ["example/toast-demo.vue"],
  // },
  // {
  //   name: "toast-destructive",
  //   type: "components:example",
  //   registryDependencies: ["toast"],
  //   files: ["example/toast-destructive.vue"],
  // },
  // {
  //   name: "toast-simple",
  //   type: "components:example",
  //   registryDependencies: ["toast"],
  //   files: ["example/toast-simple.vue"],
  // },
  // {
  //   name: "toast-with-action",
  //   type: "components:example",
  //   registryDependencies: ["toast"],
  //   files: ["example/toast-with-action.vue"],
  // },
  // {
  //   name: "toast-with-title",
  //   type: "components:example",
  //   registryDependencies: ["toast"],
  //   files: ["example/toast-with-title.vue"],
  // },
  // {
  //   name: "toggle-demo",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-demo.vue"],
  // },
  // {
  //   name: "toggle-disabled",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-disabled.vue"],
  // },
  // {
  //   name: "toggle-lg",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-lg.vue"],
  // },
  // {
  //   name: "toggle-outline",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-outline.vue"],
  // },
  // {
  //   name: "toggle-sm",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-sm.vue"],
  // },
  // {
  //   name: "toggle-with-text",
  //   type: "components:example",
  //   registryDependencies: ["toggle"],
  //   files: ["example/toggle-with-text.vue"],
  // },
  // {
  //   name: "tooltip-demo",
  //   type: "components:example",
  //   registryDependencies: ["tooltip"],
  //   files: ["example/tooltip-demo.vue"],
  // },
  // {
  //   name: "typography-blockquote",
  //   type: "components:example",
  //   files: ["example/typography-blockquote.vue"],
  // },
  // {
  //   name: "typography-demo",
  //   type: "components:example",
  //   files: ["example/typography-demo.vue"],
  // },
  // {
  //   name: "typography-h1",
  //   type: "components:example",
  //   files: ["example/typography-h1.vue"],
  // },
  // {
  //   name: "typography-h2",
  //   type: "components:example",
  //   files: ["example/typography-h2.vue"],
  // },
  // {
  //   name: "typography-h3",
  //   type: "components:example",
  //   files: ["example/typography-h3.vue"],
  // },
  // {
  //   name: "typography-h4",
  //   type: "components:example",
  //   files: ["example/typography-h4.vue"],
  // },
  // {
  //   name: "typography-inline-code",
  //   type: "components:example",
  //   files: ["example/typography-inline-code.vue"],
  // },
  // {
  //   name: "typography-large",
  //   type: "components:example",
  //   files: ["example/typography-large.vue"],
  // },
  // {
  //   name: "typography-lead",
  //   type: "components:example",
  //   files: ["example/typography-lead.vue"],
  // },
  // {
  //   name: "typography-list",
  //   type: "components:example",
  //   files: ["example/typography-list.vue"],
  // },
  // {
  //   name: "typography-muted",
  //   type: "components:example",
  //   files: ["example/typography-muted.vue"],
  // },
  // {
  //   name: "typography-p",
  //   type: "components:example",
  //   files: ["example/typography-p.vue"],
  // },
  // {
  //   name: "typography-small",
  //   type: "components:example",
  //   files: ["example/typography-small.vue"],
  // },
  // {
  //   name: "typography-table",
  //   type: "components:example",
  //   files: ["example/typography-table.vue"],
  // },
  // {
  //   name: "mode-toggle",
  //   type: "components:example",
  //   files: ["example/mode-toggle.vue"],
  // },
  // {
  //   name: "cards",
  //   type: "components:example",
  //   files: ["example/cards/cards.vue"],
  // },
]

export const registry: Registry = [...ui, ...example]
